### ISSUE TITLE
Add CI step to push to PyPI

### ISSUE THREAD

**Issue by thompson318** [UCL/scikit-surgery#23]
In GitLab by @ThomasDowrick on Nov 16, 2018, 13:27

This can be a manual option in the pipeline, and only avaialable when a tagged version has been pushed to master.

Tom Doel provided this sample code below. $PYPI_USER and $PYPI_PASS need to be store as gitlab variables.

```
deploy pip to production:
  stage: deploy
  when: manual
  only:
    - tags
  environment:
    name: PyPI
    url: https://pypi.python.org/pypi/PROJECT-NAME
  tags:
    - pip-production
  artifacts:
    paths:
    - dist/
  script:
    # remove any previous distribution files
    - rm -rf dist

    # bundle installer
    - python setup.py bdist_wheel

    # Upload to testpypi server
    - twine upload --repository pypi dist/* --username $PYPI_USER --password $PYPI_PASS

```
