### ISSUE TITLE
Create/push a python package to PyPi using a) setup.py file b) python wheel

### ISSUE THREAD

**Issue by thompson318** [UCL/scikit-surgery#8]
In GitLab by @ThomasDowrick on Oct 5, 2018, 13:37

Any python package can be uploaded to the Python Package Index (PyPI), providing 'pip install xyz' functionality.

Check we can do this using the existing Python Template project (or adjust if neccessary).

**Comment by thompson318** [comment]
In GitLab by @ThomasDowrick on Oct 10, 2018, 14:45

The PythonTemplate project creates a setup.py file, that is used to create distributable packages.

If the dependencies are correctly specificed in setup.py, then it is possible to install all the dependencies for a package by:
``` git clone https://weisslab.cs.ucl.ac.uk/WEISS/SoftwareRepositories/ardavin```
``` python setup.py install```

## Distributing source code
Rather than having to clone the entire repository, an source archive or binary wheel file can be distributed instead:

**Install necessary packages** ```pip install setuptools wheel```

**Create source distribution**  ```python setup.py sdist```

**Create wheel**  ```python setup.py bdist_wheel```

More details on wheels can be found at https://pythonwheels.com/

## Pushing to Pypi

The process is explained in detail at https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/

In brief:

Create an account on PyPI (best to also create on on the PyPi test server too)
create a ~/.pypirc file which details the repository (pypi/pypi-test etc.)
use *twine* (python library) to upload the package.

I have successfuly worked through the steps, which are relatively straightforward. Once I've got my head around it a bit more I will add some documentation and/or update the PythonTemplate repo where needed.

**Comment by thompson318** [comment]
In GitLab by @MattClarkson on Nov 6, 2018, 21:48

THis looks useful. Is it worth testing this out, sooner rather than later, for Pypi sdists at least, even if we are not doing a wheel? If the PythonTemplate needs updating, then its best to do this before we start propagating too many repos without it.

**Comment by thompson318** [comment]
In GitLab by @ThomasDowrick on Nov 7, 2018, 09:41

We should certainly get this up and running for our existing projects soon - it will make things much easier in terms of dependency management when we are doing GUIs that pull in different libraries (sksurgeryimage, overlay, tracking etc.)

This seems to be a good guide for GitLab (https://medium.com/@pypripackages/using-gitlab-pipelines-to-deploy-python-packages-in-production-and-staging-environments-8ab7dc979274). I can take a look at this next week.

I'm not convinced that it would need to be enabled by default in PythonTemplate, as not everyone is going to want/need to push to PyPi, but we can have it as an option.

**Comment by thompson318** [comment]
In GitLab by @MattClarkson on Nov 7, 2018, 09:44

Could it just be a tox task, that didnt run by default? I'm not sure I'd want CI builds to push to PyPi.  @TomDoel @StephenThompson

**Comment by thompson318** [comment]
In GitLab by @ThomasDowrick on Nov 7, 2018, 09:50

The method used in the link above only pushes to PyPi if you push a tagged (v1/v2/whatever) commit to master. Otherwise it can go to a private package repository, or just be ignored.

**Comment by thompson318** [comment]
In GitLab by @TomDoel on Nov 7, 2018, 10:29

@MattClarkson @ThomasDowrick you can have manual jobs in GitLab CI using `when:manual`. You trigger them manually on the GitLab user interface (a play button appears next to the job). You can further specify that this manual job is only available when a tag is pushed. 

That's how I did it for the python ImageSplit project; I've copied in the sample CI code below for reference. The `environment` link just give you a direct link to the PyPi website from the job.

``` 
deploy pip to production:
  stage: deploy
  when: manual
  only:
    - tags
  environment:
    name: PyPI
    url: https://pypi.python.org/pypi/PROJECT-NAME
  tags:
    - pip-production
  artifacts:
    paths:
    - dist/
  script:
    # remove any previous distribution files
    - rm -rf dist

    # bundle installer
    - python setup.py bdist_wheel

    # Upload to testpypi server
    - twine upload --repository pypi dist/* --username $PYPI_USER --password $PYPI_PASS
```
